# Generated by Django 5.2.8 on 2025-11-22 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cableoperadores', '0004_alter_cableoperadores_nombre_largo'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoProyecto',
            fields=[
                ('OT_PRST', models.CharField(blank=True, max_length=100, null=True, verbose_name='OT PRST')),
                ('OT_AIRE', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='OT Air-e')),
                ('nombre', models.CharField(max_length=100)),
                ('rechazado_GD', models.BooleanField(default=False, verbose_name='¿Rechazado GD?')),
                ('cancelado', models.BooleanField(default=False, verbose_name='¿Cancelado?')),
                ('incluir_contrato', models.BooleanField(default=False, verbose_name='¿Incluir en Contrato?')),
                ('negado', models.BooleanField(default=False, verbose_name='¿Negado?')),
                ('TipoIngreso', models.CharField(choices=[('Viabilidad', 'Viabilidad'), ('Desmonte', 'Desmonte'), ('Legalizacion', 'Legalizacion')], default='Viabilidad', max_length=100)),
                ('departamento', models.CharField(choices=[('atlantico', 'Atlantico'), ('magdalena', 'Magdalena'), ('la_guajira', 'La Guajira')], max_length=20)),
                ('municipio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Municipio')),
                ('barrio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Barrio')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_confirmacion_fin', models.DateField(blank=True, null=True)),
                ('fecha_radicacion_prst', models.DateField(blank=True, null=True)),
                ('fecha_revision_doc', models.DateField(blank=True, null=True)),
                ('fecha_entrega_coordinador', models.DateField(auto_now_add=True, null=True)),
                ('estado_ingreso', models.CharField(blank=True, choices=[('En_proceso', 'En proceso'), ('cancelado', 'Cancelado'), ('rechazado_GD', 'Rechazado GD'), ('incluir_contrato', 'Incluir en Contrato'), ('negado', 'Negado')], default='En_proceso', max_length=100, null=True, verbose_name='Registro de estado del proyecto')),
                ('observaciones', models.TextField(blank=True, max_length=1000, null=True)),
                ('cableoperador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cableoperadores.cableoperadores', verbose_name='Cableoperador')),
            ],
            options={
                'db_table': 'ingreso_proyecto',
            },
        ),
        migrations.CreateModel(
            name='AlturaInicialPoste',
            fields=[
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='proyectos.ingresoproyecto', verbose_name='Proyecto')),
                ('tipo8', models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 8')),
                ('tipo9', models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 9')),
                ('tipo10', models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 10')),
                ('tipo11', models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 11')),
                ('tipo12', models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 12')),
                ('tipo14', models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 14')),
                ('tipo16', models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 16')),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('datos_ingreso', models.ForeignKey(db_column='datos_ingreso_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='proyectos.ingresoproyecto')),
                ('estado_actual', models.CharField(max_length=100)),
                ('fecha_inspeccion', models.DateField()),
                ('fecha_analisis_inspeccion', models.DateField()),
            ],
            options={
                'db_table': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='proyectos.proyectos', verbose_name='Proyecto Asociado')),
                ('tipo8', models.PositiveIntegerField(default=0, verbose_name='8 metros')),
                ('tipo10', models.PositiveIntegerField(default=0, verbose_name='10 metros')),
                ('tipo12', models.PositiveIntegerField(default=0, verbose_name='12 metros')),
                ('tipo14', models.PositiveIntegerField(default=0, verbose_name='14 metros')),
                ('tipo15', models.PositiveIntegerField(default=0, verbose_name='15 metros')),
                ('tipo16', models.PositiveIntegerField(default=0, verbose_name='16 metros')),
                ('tipo20', models.PositiveIntegerField(default=0, verbose_name='20 metros')),
            ],
            options={
                'db_table': 'Cables_proyecto',
            },
        ),
        migrations.CreateModel(
            name='Caja_empalme',
            fields=[
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='proyectos.proyectos', verbose_name='Proyecto Asociado')),
                ('tipo8', models.PositiveIntegerField(default=0, verbose_name='8 metros')),
                ('tipo10', models.PositiveIntegerField(default=0, verbose_name='10 metros')),
                ('tipo12', models.PositiveIntegerField(default=0, verbose_name='12 metros')),
                ('tipo14', models.PositiveIntegerField(default=0, verbose_name='14 metros')),
                ('tipo15', models.PositiveIntegerField(default=0, verbose_name='15 metros')),
                ('tipo16', models.PositiveIntegerField(default=0, verbose_name='16 metros')),
                ('tipo20', models.PositiveIntegerField(default=0, verbose_name='20 metros')),
            ],
            options={
                'db_table': 'Cajas_empalme_proyectos',
            },
        ),
        migrations.CreateModel(
            name='Nap',
            fields=[
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='proyectos.proyectos', verbose_name='Proyecto Asociado')),
                ('tip8', models.PositiveIntegerField(default=0, verbose_name='8 metros')),
                ('tip10', models.PositiveIntegerField(default=0, verbose_name='10 metros')),
                ('tip12', models.PositiveIntegerField(default=0, verbose_name='12 metros')),
                ('tip14', models.PositiveIntegerField(default=0, verbose_name='14 metros')),
                ('tip15', models.PositiveIntegerField(default=0, verbose_name='15 metros')),
                ('tip16', models.PositiveIntegerField(default=0, verbose_name='16 metros')),
                ('tip20', models.PositiveIntegerField(default=0, verbose_name='20 metros')),
            ],
            options={
                'db_table': 'Naps_proyectos',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='proyectos.proyectos', verbose_name='Proyecto Asociado')),
                ('tipo8', models.PositiveIntegerField(default=0, verbose_name='8 metros')),
                ('tipo10', models.PositiveIntegerField(default=0, verbose_name='10 metros')),
                ('tipo12', models.PositiveIntegerField(default=0, verbose_name='12 metros')),
                ('tipo14', models.PositiveIntegerField(default=0, verbose_name='14 metros')),
                ('tipo15', models.PositiveIntegerField(default=0, verbose_name='15 metros')),
                ('tipo16', models.PositiveIntegerField(default=0, verbose_name='16 metros')),
                ('tipo20', models.PositiveIntegerField(default=0, verbose_name='20 metros')),
            ],
            options={
                'db_table': 'Reservas_proyectos',
            },
        ),
    ]
