# Generated by Django 5.2.8 on 2025-11-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='estado_inicial',
            field=models.CharField(choices=[('gesionar_escritorio', 'Gestionar desde Escritorio'), ('gesionar_sitio', 'Gestionar in Sitio')], default='gesionar_escritorio', max_length=100),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='fecha_entrega_pj',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='fecha_notificacion_prst',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingresoproyecto',
            name='estado_ingreso',
            field=models.CharField(blank=True, choices=[('En_proceso', 'En proceso'), ('cancelado', 'Cancelado'), ('rechazado_GD', 'Rechazado GD'), ('incluir_contrato', 'Incluir en Contrato'), ('negado', 'Negado'), ('aprobado', 'Aprobado')], default='En_proceso', max_length=100, null=True, verbose_name='Registro de estado del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='fecha_analisis_inspeccion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='fecha_inspeccion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
