# Generated by Django 5.2.8 on 2025-11-21 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresoproyecto',
            name='altura_inicial_poste',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='OT_AIRE',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='id',
        ),
        migrations.AddField(
            model_name='ingresoproyecto',
            name='OT_AIRE',
            field=models.CharField(default='1', max_length=100, primary_key=True, serialize=False, verbose_name='OT Air-e'),
        ),
        migrations.AlterField(
            model_name='alturainicialposte',
            name='proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='proyectos.ingresoproyecto', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='ingresoproyecto',
            name='estado_ingreso',
            field=models.CharField(blank=True, choices=[('En_proceso', 'En proceso'), ('cancelado', 'Cancelado'), ('rechazado_GD', 'Rechazado GD'), ('incluir_contrato', 'Incluir en Contrato'), ('negado', 'Negado')], default='En_proceso', max_length=100, null=True, verbose_name='Registro de estado del proyecto'),
        ),
        migrations.AlterField(
            model_name='ingresoproyecto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='datos_ingreso',
            field=models.ForeignKey(db_column='datos_ingreso_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='proyectos.ingresoproyecto'),
        ),
    ]
