# Generated by Django 5.2.8 on 2025-11-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_remove_ingresoproyecto_altura_inicial_poste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoproyecto',
            name='OT_AIRE',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='OT Air-e'),
        ),
    ]
