# Generated by Django 5.2.8 on 2025-11-26 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyectos_estado_inicial_proyectos_fecha_entrega_pj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlturaFinalPoste',
            fields=[
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='proyectos.proyectos', verbose_name='Proyecto')),
                ('tipo8', models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 8')),
                ('tipo9', models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 9')),
                ('tipo10', models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 10')),
                ('tipo11', models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 11')),
                ('tipo12', models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 12')),
                ('tipo14', models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 14')),
                ('tipo16', models.IntegerField(default=0, verbose_name='Ingrese cantidad de Poste de Altura 16')),
            ],
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='datos_ingreso',
            field=models.OneToOneField(db_column='datos_ingreso_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='proyectos.ingresoproyecto'),
        ),
    ]
