# Generated by Django 5.2.8 on 2025-11-26 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectores', '0001_initial'),
        ('proyectos', '0003_alturafinalposte_alter_proyectos_datos_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='estado_inicial',
            field=models.CharField(choices=[('gestionar_escritorio', 'Gestionar desde Escritorio'), ('gestionar_sitio', 'Gestionar in Sitio')], default='gesionar_escritorio', max_length=100),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='inspector_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='inspectores.inspectores', verbose_name='Inspector Responsable'),
        ),
    ]
