# Generated by Django 5.2.8 on 2025-11-12 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0002_remove_contratos_tipo_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mes_uso', models.DateField(verbose_name='Mes de Uso')),
                ('Fecha_facturacion', models.DateField(verbose_name='Fecha de Facturación')),
                ('Num_factura', models.CharField(max_length=50, verbose_name='Número de Factura')),
                ('Valor_facturado_iva', models.FloatField(max_length=50, verbose_name='Valor IVA')),
                ('Valor_iva_millones', models.FloatField(verbose_name='Valor en millones')),
                ('Fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('Periodo_vencimiento', models.DateField(verbose_name='Periodo de Vencimiento')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('PagadaParcial', 'Pago Parcial'), ('Pagada', 'Pagada'), ('Anulada', 'Anulada')], default='Pendiente', max_length=20, verbose_name='Estado de Pago')),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Total')),
                ('monto_pendiente', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Pendiente')),
                ('contratos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.contratos')),
            ],
            options={
                'db_table': 'Facturacion',
            },
        ),
        migrations.CreateModel(
            name='registro_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(verbose_name='Fecha pago')),
                ('periodo_pago', models.DateField(verbose_name='Periodo pago')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('facturacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturacion.facturacion')),
            ],
            options={
                'db_table': 'Registro_pago',
            },
        ),
    ]
