# Generated by Django 5.2.8 on 2025-12-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturacion',
            name='monto_pendiente',
        ),
        migrations.RemoveField(
            model_name='facturacion',
            name='monto_total',
        ),
    ]
