# Generated by Django 5.2.8 on 2025-12-11 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cableoperadores', '0001_initial'),
        ('facturacion', '0002_remove_facturacion_monto_pendiente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturacion',
            name='contratos',
        ),
        migrations.AddField(
            model_name='facturacion',
            name='cableoperador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cableoperadores.cableoperadores'),
        ),
    ]
