# Generated by Django 5.2.8 on 2025-12-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_remove_facturacion_contratos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_pago',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
