# Generated by Django 5.2.8 on 2025-12-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_alter_registro_pago_monto_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacion',
            name='Factura_CRC',
            field=models.BooleanField(default=False, verbose_name='Factura CRC'),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='Factura_aceptada',
            field=models.BooleanField(default=True, verbose_name='Factura Aceptada'),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='Fecha_aplicacion',
            field=models.DateField(blank=True, max_length=50, null=True, verbose_name='Fecha de aplicacion'),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='Fecha_confirmacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de confirmacion'),
        ),
    ]
