# Generated by Django 5.2.7 on 2025-10-23 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cableoperadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre (Obligatorio)')),
                ('nombre_largo', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('NIT', models.IntegerField(blank=True, null=True, unique=True)),
                ('Digito_verificacion', models.IntegerField(blank=True, null=True, verbose_name='Digito de verificación')),
                ('RegistroTic', models.BigIntegerField(blank=True, null=True, verbose_name='Registro TIC')),
                ('CodigoInterno', models.BigIntegerField(blank=True, null=True, verbose_name='Codigo Interno')),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('Representante', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.BigIntegerField(verbose_name='Teléfono (Obligatorio)')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo (Obligatorio)')),
                ('observaciones', models.TextField(max_length=1000, verbose_name='Observaciones (Obligatorio)')),
                ('estado', models.CharField(choices=[('Contratado', 'Contratado'), ('Finalizado', 'Finalizado'), ('En_Renovacion', 'En Renovacion'), ('Renovacion_firma_prst', 'En Renovacion - Firma PRST'), ('Renovacion_firma_air_e', 'En Renovacion - Firma AIR-E'), ('nuevo_firma_prst', 'Nuevo - Firma PRST'), ('nuevo_firma_air_e', 'Nuevo - Firma AIR-E'), ('En_Gestion', 'En Gestion'), ('Sin_usos', 'Sin Usos')], max_length=100, verbose_name='Estado (Obligatorio)')),
                ('vencimiento_factura', models.PositiveIntegerField(blank=True, null=True)),
                ('preliquidacion_num', models.PositiveIntegerField(blank=True, null=True, verbose_name='Preliquidacion Numero')),
                ('preliquidacion_letra', models.CharField(blank=True, max_length=100, null=True, verbose_name='Preliquidacion Letra')),
                ('respuesta_preliquidacion', models.CharField(blank=True, choices=[('Calendarios', 'Calendarios'), ('Habiles', 'Habiles')], max_length=100, null=True, verbose_name='Respuesta Preliquidacion')),
                ('ejecutiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cableoperadores',
            },
        ),
    ]
