# Generated by Django 5.2.7 on 2025-11-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cableoperadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cableoperadores',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
