# Generated by Django 5.2.8 on 2025-11-06 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cableoperadores', '0002_cableoperadores_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_notificacion', models.CharField(choices=[('cobro_multa', 'Cobro de Multa'), ('suspension_nuevos_accesos', 'Suspensión de Nuevos Accesos'), ('cobro_prejuridico', 'Cobro Prejurídico'), ('incumplimiento_pago_factura', 'Incumplimiento de Pago de Factura')], default='cobro_multa', max_length=100)),
                ('fecha', models.DateField()),
                ('cableoperador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cableoperadores.cableoperadores')),
            ],
        ),
    ]
