# Generated by Django 5.2.8 on 2025-11-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cableoperadores', '0003_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cableoperadores',
            name='nombre_largo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Largo'),
        ),
    ]
