# Generated by Django 5.2.8 on 2025-11-24 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cableoperadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_contrato', models.CharField(choices=[('Vigente', 'Vigente'), ('Vencido', 'Vencido')], max_length=100, verbose_name='Estado de Contrato')),
                ('duracion_anos', models.IntegerField(default=0, verbose_name='Duración en años')),
                ('inicio_vigencia', models.DateField()),
                ('fin_vigencia', models.DateField()),
                ('valor_contrato', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Valor del Contrato')),
                ('numero_poliza_cumplimiento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Póliza')),
                ('vigencia_amparo_poliza_cumplimiento', models.CharField(blank=True, choices=[('Igual_a_Duracion_de_Contrato_mas_12_Meses', 'Igual a Duración de Contrato + 12 Meses'), ('Igual_a_Duracion_de_Contrato_mas_6_Meses', 'Igual a Duración de Contrato + 6 Meses'), ('Igual_a_Duracion_de_Contrato_mas_4_Meses', 'Igual a Duración de Contrato + 4 Meses'), ('Igual_a_Duracion_de_Contrato_mas_2_Meses', 'Igual a Duración de Contrato + 2 Meses')], max_length=100, null=True, verbose_name='Vigencia de Amparo')),
                ('inicio_vigencia_poliza_cumplimiento', models.DateField(blank=True, null=True, verbose_name='Inicio de Vigencia')),
                ('fin_vigencia_poliza_cumplimiento', models.DateField(blank=True, null=True, verbose_name='Fin de Vigencia')),
                ('monto_asegurado_poliza_cumplimiento', models.CharField(blank=True, choices=[('15%_valor_contrato', '15% Valor del Contrato'), ('20%_valor_contrato', '20% Valor del Contrato'), ('30%_valor_contrato', '30% Valor del Contrato'), ('20%_valor_base_constitucion_poliza', '20% Valor base de Constitución de Póliza'), ('30%_valor_base_constitucion_poliza', '30% Valor base de Constitución de Póliza')], max_length=100, null=True, verbose_name='Monto Asegurado')),
                ('valor_monto_asegurado_poliza_cumplimiento', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor del Monto Asegurado')),
                ('valor_asegurado_poliza_cumplimiento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor Asegurado')),
                ('inicio_amparo_poliza_cumplimiento', models.DateField(blank=True, null=True, verbose_name='Inicio de Amparo')),
                ('fin_amparo_poliza_cumplimiento', models.DateField(blank=True, null=True, verbose_name='Fin de Amparo')),
                ('expedicion_poliza_cumplimiento', models.DateField(blank=True, null=True, verbose_name='Expedición de Póliza')),
                ('numero_poliza_rce', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Póliza')),
                ('vigencia_amparo_poliza_rce', models.CharField(blank=True, choices=[('Igual_a_Duracion_de_Contrato_mas_12_Meses', 'Igual a Duración de Contrato + 12 Meses'), ('Igual_a_Duracion_de_Contrato_mas_6_Meses', 'Igual a Duración de Contrato + 6 Meses'), ('Igual_a_Duracion_de_Contrato_mas_4_Meses', 'Igual a Duración de Contrato + 4 Meses'), ('Igual_a_Duracion_de_Contrato_mas_2_Meses', 'Igual a Duración de Contrato + 2 Meses')], max_length=100, null=True, verbose_name='Vigencia de Amparo')),
                ('inicio_vigencia_poliza_rce', models.DateField(blank=True, null=True, verbose_name='Inicio de Vigencia')),
                ('fin_vigencia_poliza_rce', models.DateField(blank=True, null=True, verbose_name='Fin de Vigencia')),
                ('monto_asegurado_poliza_rce', models.CharField(blank=True, choices=[('no_inferior_100_SMLMV', 'No inferior a 100 SMLMV'), ('no_inferior_200_SMLMV', 'No inferior a 200 SMLMV'), ('no_inferior_300_SMLMV', 'No inferior a 300 SMLMV')], max_length=100, null=True, verbose_name='Monto Asegurado')),
                ('valor_monto_asegurado_poliza_rce', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor del Monto Asegurado')),
                ('valor_asegurado_poliza_rce', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor Asegurado')),
                ('inicio_amparo_poliza_rce', models.DateField(blank=True, null=True, verbose_name='Inicio de Amparo')),
                ('fin_amparo_poliza_rce', models.DateField(blank=True, null=True, verbose_name='Fin de Amparo')),
                ('expedicion_poliza_rce', models.DateField(blank=True, null=True, verbose_name='Expedición de Póliza')),
                ('tomador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tomador')),
                ('aseguradora', models.CharField(blank=True, max_length=100, null=True, verbose_name='Aseguradora')),
                ('fecha_radicacion', models.IntegerField(verbose_name='Fecha de Radicación')),
                ('tipo_fecha_radicacion', models.CharField(choices=[('fija', 'Fija'), ('dinamica', 'Dinámica')], max_length=100, verbose_name='Tipo de Fecha de Radicación')),
                ('fecha_preliquidacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Preliquidación')),
                ('cableoperador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cableoperadores.cableoperadores')),
            ],
            options={
                'db_table': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contratos.contratos', verbose_name='Contrato Asociado')),
                ('tipo8', models.PositiveIntegerField(default=0, verbose_name='8 metros')),
                ('tipo10', models.PositiveIntegerField(default=0, verbose_name='10 metros')),
                ('tipo12', models.PositiveIntegerField(default=0, verbose_name='12 metros')),
                ('tipo14', models.PositiveIntegerField(default=0, verbose_name='14 metros')),
                ('tipo15', models.PositiveIntegerField(default=0, verbose_name='15 metros')),
                ('tipo16', models.PositiveIntegerField(default=0, verbose_name='16 metros')),
                ('tipo20', models.PositiveIntegerField(default=0, verbose_name='20 metros')),
            ],
            options={
                'db_table': 'Cables',
            },
        ),
        migrations.CreateModel(
            name='Caja_empalme',
            fields=[
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contratos.contratos', verbose_name='Contrato Asociado')),
                ('tipo8', models.PositiveIntegerField(default=0, verbose_name='8 metros')),
                ('tipo10', models.PositiveIntegerField(default=0, verbose_name='10 metros')),
                ('tipo12', models.PositiveIntegerField(default=0, verbose_name='12 metros')),
                ('tipo14', models.PositiveIntegerField(default=0, verbose_name='14 metros')),
                ('tipo15', models.PositiveIntegerField(default=0, verbose_name='15 metros')),
                ('tipo16', models.PositiveIntegerField(default=0, verbose_name='16 metros')),
                ('tipo20', models.PositiveIntegerField(default=0, verbose_name='20 metros')),
            ],
            options={
                'db_table': 'Cajas_empalme',
            },
        ),
        migrations.CreateModel(
            name='Nap',
            fields=[
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contratos.contratos', verbose_name='Contrato Asociado')),
                ('tip8', models.PositiveIntegerField(default=0, verbose_name='8 metros')),
                ('tip10', models.PositiveIntegerField(default=0, verbose_name='10 metros')),
                ('tip12', models.PositiveIntegerField(default=0, verbose_name='12 metros')),
                ('tip14', models.PositiveIntegerField(default=0, verbose_name='14 metros')),
                ('tip15', models.PositiveIntegerField(default=0, verbose_name='15 metros')),
                ('tip16', models.PositiveIntegerField(default=0, verbose_name='16 metros')),
                ('tip20', models.PositiveIntegerField(default=0, verbose_name='20 metros')),
            ],
            options={
                'db_table': 'Naps',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contratos.contratos', verbose_name='Contrato Asociado')),
                ('tipo8', models.PositiveIntegerField(default=0, verbose_name='8 metros')),
                ('tipo10', models.PositiveIntegerField(default=0, verbose_name='10 metros')),
                ('tipo12', models.PositiveIntegerField(default=0, verbose_name='12 metros')),
                ('tipo14', models.PositiveIntegerField(default=0, verbose_name='14 metros')),
                ('tipo15', models.PositiveIntegerField(default=0, verbose_name='15 metros')),
                ('tipo16', models.PositiveIntegerField(default=0, verbose_name='16 metros')),
                ('tipo20', models.PositiveIntegerField(default=0, verbose_name='20 metros')),
            ],
            options={
                'db_table': 'Reservas',
            },
        ),
    ]
