# Generated by Django 5.2.7 on 2025-10-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='tipo_contrato',
        ),
    ]
