# Generated by Django 5.2.8 on 2025-11-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nap',
            old_name='tip10',
            new_name='tipo10',
        ),
        migrations.RenameField(
            model_name='nap',
            old_name='tip12',
            new_name='tipo12',
        ),
        migrations.RenameField(
            model_name='nap',
            old_name='tip14',
            new_name='tipo14',
        ),
        migrations.RenameField(
            model_name='nap',
            old_name='tip15',
            new_name='tipo15',
        ),
        migrations.RenameField(
            model_name='nap',
            old_name='tip16',
            new_name='tipo16',
        ),
        migrations.RenameField(
            model_name='nap',
            old_name='tip20',
            new_name='tipo20',
        ),
        migrations.RenameField(
            model_name='nap',
            old_name='tip8',
            new_name='tipo8',
        ),
    ]
