# Generated by Django 5.2.8 on 2025-12-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_rename_tip10_nap_tipo10_rename_tip12_nap_tipo12_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='estado_contrato',
            field=models.CharField(choices=[('Vigente', 'Vigente'), ('Vencido', 'Vencido'), ('Pendiente', 'Pendiente')], max_length=100, verbose_name='Estado de Contrato'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='fecha_radicacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fecha de Radicación'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='fin_vigencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='inicio_vigencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='tipo_fecha_radicacion',
            field=models.CharField(blank=True, choices=[('fija', 'Fija'), ('dinamica', 'Dinámica')], max_length=100, null=True, verbose_name='Tipo de Fecha de Radicación'),
        ),
    ]
