# Generated by Django 5.2.8 on 2025-12-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_alter_contratos_estado_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='monto_asegurado_poliza_cumplimiento',
            field=models.CharField(blank=True, choices=[('15%_valor_contrato', '15% Valor del Contrato'), ('20%_valor_contrato', '20% Valor del Contrato'), ('30%_valor_contrato', '30% Valor del Contrato'), ('20%_valor_base_constitucion_poliza', '20% Valor base de Constitución de Póliza'), ('30%_valor_base_constitucion_poliza', '30% Valor base de Constitución de Póliza'), ('no_inferior_100_SMLMV', 'No inferior a 100 SMLMV'), ('no_inferior_200_SMLMV', 'No inferior a 200 SMLMV'), ('no_inferior_300_SMLMV', 'No inferior a 300 SMLMV')], max_length=100, null=True, verbose_name='Monto Asegurado'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='monto_asegurado_poliza_rce',
            field=models.CharField(blank=True, choices=[('15%_valor_contrato', '15% Valor del Contrato'), ('20%_valor_contrato', '20% Valor del Contrato'), ('30%_valor_contrato', '30% Valor del Contrato'), ('20%_valor_base_constitucion_poliza', '20% Valor base de Constitución de Póliza'), ('30%_valor_base_constitucion_poliza', '30% Valor base de Constitución de Póliza'), ('no_inferior_100_SMLMV', 'No inferior a 100 SMLMV'), ('no_inferior_200_SMLMV', 'No inferior a 200 SMLMV'), ('no_inferior_300_SMLMV', 'No inferior a 300 SMLMV')], max_length=100, null=True, verbose_name='Monto Asegurado'),
        ),
    ]
