"""
Django settings for API project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w_os@!-e9hvlw7j0$9ddpt&b%42)-xq_r6yul(0nfu@7p@gg4m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'cableoperadores',
    'contratos',
    'facturacion',
    'authentication',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # corsheaders
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]
# 🛑 CONFIGURACIÓN DE CORS
# CORS_ALLOWED_ORIGINS = [
#     "http://127.0.0.1:5500",  # El servidor live-server o VS Code
#     "http://localhost:5500",  # Si usas localhost en lugar de 127.0.0.1
#     # Añade cualquier otro frontend que uses, ej: "http://dominio-web.com"
# ]

# Si quieres permitir que cualquier origen acceda (solo recomendado para desarrollo/pruebas)
CORS_ALLOW_ALL_ORIGINS = True
# 🛑 AÑADE ESTA LÍNEA para el chequeo de seguridad CSRF
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:5500', # Permite que este origen haga POST/PUT/DELETE
    'http://localhost:5500',
    'https://adrian04g.github.io/Air-e-app/'
    # Si tienes un subdominio o usas HTTPS, añádelo aquí
    # 'https://*.example.com',
]
ROOT_URLCONF = 'API.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'API.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'mydatabase',
#         'USER': 'root',
#         'PASSWORD': 'apr.1234',
#         'HOST': 'localhost',
#         'PORT': '3306',
#         'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"}
#     }
# }
import os

from dotenv import load_dotenv
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.

# DB_PASSWORD: str = os.environ.get("DB_PASSWORD")
# DB_HOST: str = os.environ.get("DB_HOST")
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DB_NAME'),       # Carga el nombre de la DB
#         'USER': os.getenv('DB_USER'),       # Carga el usuario
#         'PASSWORD': os.getenv('DB_PASSWORD'), # Carga la contraseña
#         #'HOST': 'aws-1-us-east-1.pooler.supabase.com',       # Carga el host
#         'HOST': os.getenv('DB_HOST'),       # Carga el host
#         'PORT': os.getenv('DB_PORT'),       # Carga el puerto
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# settings.py

CACHES = {
    'default': {
        # SOLUCIÓN AL ERROR: Usamos FileBasedCache para estabilidad. 
        # IMPORTANTE: Ya no usamos delete_pattern en views.py, usamos cache.clear().
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        
        # 🚨 FIX W003: Usar una ruta absoluta basada en BASE_DIR
        # Esto crea una carpeta 'cache_files' dentro de la raíz de tu proyecto.
        'LOCATION': '/tmp/django_cache',
        
        # Opciones 
        'TIMEOUT': 900, # 15 minutos (900 segundos)
        'OPTIONS': {
            'MAX_ENTRIES': 1000, 
        }
    }
}


# 🚨 Configuración opcional de Middleware de Caché 
# (No necesario para el caching de vistas con @cache_page, pero bueno saberlo)

# MIDDLEWARE = [
#     'django.middleware.cache.UpdateCacheMiddleware',
#     # ... otros middlewares
#     'django.middleware.common.CommonMiddleware',
#     # ... otros middlewares
#     'django.middleware.cache.FetchFromCacheMiddleware',
# ]

# CACHE_MIDDLEWARE_SECONDS = 600 # 10 minutos para el middleware de sitio
# CACHE_MIDDLEWARE_ALIAS = 'default'
# CACHE_MIDDLEWARE_KEY_PREFIX = ''
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
     'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework_xml.renderers.XMLRenderer',
        'rest_framework_csv.renderers.CSVRenderer',
        'rest_framework_yaml.renderers.YAMLRenderer',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '2000/day',
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 49,
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}